- name: Create filesystem on SATA drive
  ansible.builtin.script: scripts/create_shared_volume.sh
  args:
    creates: /sharedfs
- name: Install packages
  ansible.builtin.apt:
    name: nfs-kernel-server
- name: Define Exported sharedfs
  lineinfile:
    path: /etc/exports
    line: "/sharedfs *(rw,sync,no_root_squash,no_subtree_check)"
- name: Enable network daemon
  ansible.builtin.systemd_service:
    name: nfs-kernel-server
    state: started
    enabled: true


